# site properties and page defaults
title: #Helene's Hobbies
subtitle: by Helene B. Thomsen
description: An engaging 1-3 sentence description of your lab.
header: # images/header.png
footer: # images/mandala.png
proofer: false
#  background-color: hsl(44, 100%, 70%);

# site social media and other links
links:
  email: helenet@live.dk
  orcid: 0009-0000-9059-3038
  # google-scholar: ETJoidYAAAAJ
  github: HeleneThomsen
  #twitter: HeleneThomsen
  #youtube: HeleneThomsen

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
